### load packages
library(DSS)
library(dmrseq)
library(ChIPseeker)
library(BiocParallel)
library(TxDb.Mmusculus.UCSC.mm10.knownGene)
library(clusterProfiler)
library(DOSE)
library(GenomicRanges)
library(fdrtool)
library(ArchR)
library(ggplot2)
library(ggfortify)
library(ggsci)
library(methylCC)
library(RColorBrewer)
library(liftOver)
library(rtracklayer)
library(DOSE)
library(DMRichR)
library(viridis)
library(enrichplot)
library(wesanderson)
txdb <- TxDb.Mmusculus.UCSC.mm10.knownGene
mmAnno <- getAnnot("mm10")

### differential analysis with dmrseq
setwd("dmrseq_Results/")
getDiff <- function(x,y,z) {
bs2 <- bs[,c(y,z)] 
loci.idx <- which(DelayedMatrixStats::rowSums2(getCoverage(bs2, type="Cov")<5) == 0)
bs.filtered <- bs2[loci.idx,]
cores <- 40
regions <- dmrseq(bs.filtered,testCovariate="Condition",maxPerms=10,minNumRegion=5,cutoff=0.1,BPPARAM=BiocParallel::MulticoreParam(workers=cores))
group1FH <- deparse(substitute(y))
group2FH <- deparse(substitute(z))
outputFH <- paste0("dss.",group1FH,"_vs_",group2FH,".rdata")
save(bs.filtered,regions,file=outputFH)
}
getDiff(bs,F0_FA,F0_DDI)
getDiff(bs,F1_FA,F1_DDI)
getDiff(bs,F2_FA,F2_DDI)
getDiff(bs,F3_FA,F3_DDI)
getDiff(bs,F4_FA,F4_DDI)
getDiff(bs,F4_Cross,F4_DDI)
getDiff(bs,F4_OCross,F4_DDI)
getDiff(bs,F4_RCross,F4_DDI)
getDiff(bs,F4_Cross,F4_FA)
getDiff(bs,F4_OCross,F4_FA)
getDiff(bs,F4_RCross,F4_FA)
getDiff(bs,F4_OCross,F4_Cross)
getDiff(bs,F4_RCross,F4_Cross)
getDiff(bs,F4_Cross,F3_FA)
getDiff(bs,F4_Cross,F3_DDI)
getDiff(bs,F4_OCross,F4_RCross)
